PROJ = uart
SRC += top.v
SRC += ../../components/gpmc-sync.v
SRC += ../../components/uart-tx.v
SRC += ../../components/uart-rx.v
SRC += ../../components/fifo.v

all: $(PROJ).bin
include ../Makefile.beaglewire
